### ISSUE TITLE
design choices

### ISSUE THREAD

**Issue by jermwatt** [jhagas/ESP32-Supabase#10]
Thanks for creating this!  I found it very helpful in getting up and running with esp + supabase.

A few thoughts on design choices. 

--- 
I don't think requiring Supabaase account credentials is necessary or helpful for using this library.   

Two reasons for this

-  IoT applications using this library will most likely consist of a single user - the individual tinkering with esps + sensors.  This makes RLS on tables redundant (there's only ever one user).  In this case to manipulate data in a supabase table all you need is the project url and anon_key. 

-  You use an account email and password to login and recieve a JWT - but I would wager most supabase users do not have an account password - since you can register via a github auth.  This how I registered, and when I tried to recover a password I recieved the modal below (indicating that its not possible for me to get one since I did not register with one in the first place)

<img width="349" alt="Screen Shot 2023-05-01 at 5 22 47 AM" src="https://user-images.githubusercontent.com/16326421/235451792-403397f2-65e9-4d35-8029-9fa18d4a9449.png">

- From the look of [your demo](https://www.jhagas.space/posts/monitoring-data-logging-sensor-iot-supabase) it appears you disabled RLS anyway for your example table(s) - so account login is redundant

---

Building on the previous point - differentiating between RLS and non-RLS usage of the library.

As mentioned above, I imagine non-RLS usage would be most common.  A simple update to the README.md / examples can explain this.

When it comes to RLS usage - the username/password flow can still be used to login authenticated users.

--- 
Storing secrets.

Good practice not have secrets stored in plain text - even in examples.  To the best of my understanding, since arduino does not have a dotenv port the best way to store secrets is in a header (e.g., Secrets.h) that you explicitly avoid pushing in your .gitignore.

For example in /examples/select instead of

```
// put your WiFi credentials (SSID and Password) here
const char *ssid = "";
const char *psswd = "";
```

you would have

```
#include <Secrets.h>

// put your WiFi credentials (SSID and Password) here
const char *ssid = WIFI_SSID;
const char *psswd = WIFI_PASSWORD;
```

where WIFI_SSID and  WIFI_PASSWORD are defined in Secrets.h.

---
---
I'm going to make these and other simplifying changes in [my fork](https://github.com/jermwatt/SupabaseESP).  Would be happy to re-merge when complete if interested, but understand some of these points are design choices (and so are subjective).

**Comment by jhagas** [comment]
> I don't think requiring Supabaase account credentials is necessary or helpful for using this library.

What i mean for supabase account is account that you make inside the supabase project, for some purpose that RLS should be enabled. It is a nice to have feature, users not required to login at all.

>  I imagine non-RLS usage would be most common

Sure it is.. That's why its not necessary to login to your account

---

> Good practice not have secrets stored in plain text - even in examples. To the best of my understanding, since arduino does not have a dotenv port the best way to store secrets is in a header (e.g., Secrets.h) that you explicitly avoid pushing in your .gitignore.

Examples could be used in let's say arduino IDE, where user could open, edit, and tinker around with examples code. Separation of secrets variable is a good idea though for a project. But, I don't think separating the secrets from examples could be useful for library's users

**Comment by jermwatt** [comment]
👍
