### ISSUE TITLE
Cannot compile Supabase.cpp

### ISSUE THREAD

**Issue by atulraj85** [jhagas/ESP32-Supabase#15]
Here is what I am doing.
1. Using PlatformIO with Vscodium.
2. Created a new project, with Arduino Framework.
3. Added your library to the project. (ESP32-Supabase)
4. Build it, now it shows error about :
```
.pio/libdeps/esp32dev/ESP32 Supabase/src/ESP32_Supabase.h:6:10: fatal error: WiFiClientSecure.h: No such file or directory
```

**Comment by atulraj85** [comment]
I just copying the "src/" contents to my project for now.

**Comment by atulraj85** [comment]
Yes it is working after copying, but it should compile like other libraries.

**Comment by jhagas** [comment]
Maybe your Platform IO didn't sets up everything yet, as WiFiClientSecure is a part of ESP32/8266 platform for Arduino
