### ISSUE TITLE
JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 1) in Select Example

### ISSUE THREAD

**Issue by ajdrodriguez** [jhagas/ESP32-Supabase#16]
This error message shows after uploading the Select example code with modified credentials.

{"code":"PGRST301","details":null,"hint":null,"message":"JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 1)"}

I used the Anon key from my Supabase table, and tried using the Service_role key, but to no avail.

**Comment by randesu** [comment]
Same error here, any update or result from you mate?

**Comment by ajdrodriguez** [comment]
> Same error here, any update or result from you mate?

Hi! I didn't use this library for this project anymore. Instead, I use [ESP8266HTTPClient.h](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h) library to initiate a GET request from the supabase server.

**Comment by randesu** [comment]
> > Same error here, any update or result from you mate?
> 
> Hi! I didn't use this library for this project anymore. Instead, I use [ESP8266HTTPClient.h](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h) library to initiate a GET request from the supabase server.

Got some tutorial how to do it mate? Especially for supabase. Website or video source is fine. Thanks in advance!

**Comment by ajdrodriguez** [comment]
> > > Same error here, any update or result from you mate?
> > 
> > 
> > Hi! I didn't use this library for this project anymore. Instead, I use [ESP8266HTTPClient.h](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h) library to initiate a GET request from the supabase server.
> 
> Got some tutorial how to do it mate? Especially for supabase. Website or video source is fine. Thanks in advance!

Here's the [Youtube video](https://www.youtube.com/watch?v=wI209WK3-VM) I used as a guide and basis for my project. You can use the link of library I put in my previous reply for the documentation and examples of it.

**Comment by jhagas** [comment]
I believe this is an error from my bad documentation, going to update it soon

**Comment by jhagas** [comment]
I cannot replicate this error, i guess that you don't setup your database correctly, and blindly try the example. The example is just an example of what you can do. The rest is your job to query the database as you want it..

Sorry again if i have a long time replying this issue
