### ISSUE TITLE
upsert always returning httpcode 409

### ISSUE THREAD

**Issue by SteynGuelen** [jhagas/ESP32-Supabase#17]
Using insert with bool upsert set to true, it is always returning error httpcode 409

 "409 already_exists Indicates that the resource already exists. Resolution: Use the upsert functionality in order to overwrite the file."

meaning the upsert does not work as intended.

**Comment by jhagas** [comment]
Sorry if i have a long time maintain this library, as i don't have much spare time for this
Thankyou for your pull request..
