### ISSUE TITLE
Connection duration

### ISSUE THREAD

**Issue by biggiu** [jhagas/ESP32-Supabase#21]
Hello and sorry if I bother you. I would like to switch from Firebase to Supabase. Libraries that run Firebase have an issue with the token expiring after 60 minutes. This blocks the procedure and forces the processor to restart. I wanted to know if even in this case there is a problem with the duration of the connection, beyond which it is necessary to restart. I have to develop a procedure linked to an ESP32CAM which must always work and must acquire data from the database for operational choices. Can all this be done with this library?
Thanks for the kind cooperation.

**Comment by jhagas** [comment]
The JWT token (if you use RLS) still be expixing in 60 minutes (you can change the setting in Supabase Web UI). But this library handle this stuff automatically by requesting new token every 60 minutes, or whatever you set in Supabase Web UI.
