### ISSUE TITLE
Implement .delete() method

### ISSUE THREAD

**Issue by jhagas** [jhagas/ESP32-Supabase#5]
I found that `<HTTPClient.h>` does not have a way to do DELETE HTTP Request
https://github.com/espressif/arduino-esp32/issues/4203

Any way to overcome this issue?

**Comment by jermwatt** [comment]
Is this necessary?

In terms of separation of concerns - an IOT device like an esp is primarily / sole task is recording and transmitting (sensor0 data.  

I can't think of a scenario where I would want my esp/arduino to be allowed to delete (sensor) data persisting off device.

I would task deletion responsibilities to the backend (supabase) and/or a frontend UX.

**Comment by jhagas** [comment]
I can think of one situation when .delete() might come in handy. CRON tasks. Yes, you can run it on a dedicated computer, however because esp32 is so inexpensive, this task is reasonable.

**Comment by jhagas** [comment]
Because of limited use cases and there's no way to implement it. I may close this issue
